services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: practica7_web
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: practica7
    depends_on:
      - db
    networks:
      - practica7_net

  db:
    image: mysql:8.0
    container_name: practica7_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practica7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - practica7_net

volumes:
  db_data:

networks:
  practica7_net:
    driver: bridge
